### ISSUE TITLE
NVT's Sync, but nothing appears in the web interface

### ISSUE THREAD

**Issue by Jarli01** [yu210148/gvm_install#36] opened 2021-04-20 13:19 UTC
Pictures are worth a thousand words, right?

![VirtualBoxVM_yuMBZYgN6J](https://user-images.githubusercontent.com/14837699/115402187-2fecc580-a1b9-11eb-980f-6509b5c4d3a6.png)

![VirtualBoxVM_2kc1OAZPBv](https://user-images.githubusercontent.com/14837699/115402193-311df280-a1b9-11eb-9262-fff72353630b.png)

![VirtualBoxVM_Fw4xYknnex](https://user-images.githubusercontent.com/14837699/115402200-324f1f80-a1b9-11eb-90fb-1203e11d15f4.png)

Trying to sort out why NVTs are still showing as as 0 of 0.

**Comment by yu210148** [comment] 2021-04-20 13:36
Humm, not sure why this would be. Let me fire up my instance and have a look.

kev.

**Comment by yu210148** [comment] 2021-04-20 13:45
I fired up a couple of instances that I'd done with the script and don't seem to be able to replicate this. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/1334385/115405623-6bd55a00-a1bc-11eb-9926-dd523b1883f4.png)

![image](https://user-images.githubusercontent.com/1334385/115406064-d38ba500-a1bc-11eb-8ce7-5c6e21b8d9e9.png)

If anyone else has run into this and can shed some light I'd appreciate it. I'm not sure if it's going to be an issue with the installer or with one of the GVM components itself.

kev.

**Comment by yu210148** [comment] 2021-04-20 13:46
Did you say that you'd run the installer twice in another issue a while back? I wonder if it could be some side-effect of that?

kev.

**Comment by Jarli01** [comment] 2021-04-20 13:58
I had, this is a new installation. I can run the nvt sync function and it pulls data down. When I attempt to setup a scan it throws a message about "Failed to find config 'long string'"

**Comment by Jarli01** [comment] 2021-04-20 15:05
I'm attempting another installation on a different host for good measure

**Comment by yu210148** [comment] 2021-04-20 15:08
Humm, yes, let me know what the result is. I'll attempt a fresh one myself when I get a chance.

kev.

**Comment by Jarli01** [comment] 2021-04-20 15:11
I'm running on Ubuntu Desktop 20.10 (cause you know, staying current and all). 

But will update here

**Comment by Jarli01** [comment] 2021-04-20 15:12
It might be worth adding a output file of everything the installer does so review these cases/troubleshoot issues.

**Comment by yu210148** [comment] 2021-04-20 15:13
Cool, I haven't tested on that version so yes, please let me know how it turns out.

**Comment by yu210148** [comment] 2021-04-20 15:15
True, in the meantime you could try piping its output to a file although I'm not sure how well that would work seeing as the thing writes other scripts which it then executes as other users. :)

kev.

**Comment by Jarli01** [comment] 2021-04-20 18:58
The new build is still has 0 NVT's, the others are populated. I'm attempting a `/opt/gvm/bin/greenbone-nvt-sync` to see if it'll force (but had previously).

Worst case I'll let it sit for 24 hours.

**Comment by yu210148** [comment] 2021-04-20 19:08
Humm, very odd. I've set up a copy of 20.10 server to test with and will
give it a go. I'll let you know what I find out.

kev.

**Comment by Jarli01** [comment] 2021-04-21 14:50
Yeah the NVT's are still blank on my system here,

![msedge_4U5ysJeot0](https://user-images.githubusercontent.com/14837699/115574107-5715c680-a28f-11eb-9970-6e13e3eb1345.png)

**Comment by yu210148** [comment] 2021-04-22 11:43
Hi again, 

I'm getting the same thing on Ubuntu 20.10 Server so I'm thinking there's something going on that's different between 20.04 and 20.10 that's causing this. I'm not sure what it is yet though. I'll post here when I figure it out. 

If anyone else seeing this has any idea please feel free to chime in. :)

kev.

**Comment by yu210148** [comment] 2021-04-22 14:14
Just as a test I re-ran it on a fresh 20.04 install and it seemed to go relatively smoothly for me on that (i.e., I got the NVTs to show up after synching them.) So, sticking with the LTS version may be an option. It also suggests that the issue is with Ubuntu 20.10 rather than with GVM 20 or the script.

While I was looking into this I did notice that Greenbone has released a version 21 so I'll try testing with that on 20.10 and see if results in anything better than what we're getting. :)

kev.

**Comment by Jarli01** [comment] 2021-04-23 14:03
I'll try a 20.04 LTS install here and confirm

**Comment by yu210148** [comment] 2021-04-27 20:07
I've adapted the script for GVM version 21 and tested it on Ubuntu 20.04 and Debian 10 with good results. When I get a chance I'll see what it does on the newer Ubuntu.

**Comment by Jarli01** [comment] 2021-04-28 15:35
I've finally gotten back to this and can confirm on the previous version of Ubuntu I get the SecInfo including the NVt's

**Comment by yu210148** [comment] 2021-04-28 16:29
Okay, cool. 

I downloaded and tried it with the 21.04 version this morning and ran into what I think is an altogether different issue where some of the components fail to compile. 

I'm leaning toward sticking to the LTS releases of Ubuntu with this or I may end up chasing my tail every six months. 20.04 is supported until 2025. By the time the next LTS comes out, I'll have 2 years to figure out how to make this work before support is dropped for 20.04.

Unless you--or anyone else--has a strong reason for needing it on the latest Ubuntu releases I'd like to close this issue off; at least for now. Of course, if anyone comes up with a way to make this work on them I'll gladly look at it.

kev.

**Comment by Jarli01** [comment] 2021-04-28 16:33
I'm fine with closing this if you are as well. It would be nice to know what is broken. 

I haven't really looked at the install script, does it create a log file of its process?

**Comment by yu210148** [comment] 2021-04-28 16:40
Thanks Dustin,

I don't have it doing logging at this point but it's getting to the point where that'd be useful. I usually just step through it manually when debugging and looking at the output on the standard and error outputs. 

kev.

**Closed by yu210148** 2021-04-28 16:40 UTC
