### ISSUE TITLE
After new installation v22 on Debain 11, web Service not available

### ISSUE THREAD

**Issue by schneemass** [yu210148/gvm_install#96] opened 2023-04-24 06:27 UTC
I have tried the installation of v22 on Debain 11. GSA is not accessible via web. In the gsad.log are only entries 

main: Could not write PID file

i think the gsad service is missing in the install-script
https://greenbone.github.io/docs/latest/22.4/source-build/index.html#id140

and new notus-scanner?
https://greenbone.github.io/docs/latest/22.4/source-build/index.html#notus-scanner

Is anyone running the v22?

**Comment by yu210148** [comment] 2023-04-24 11:26
Did GSA compile for you on Debian? I haven't tried version 22 there yet.
I'm wondering if this is related to issue 95 or if this is a separate
thing.

**Comment by schneemass** [comment] 2023-04-24 12:21
Have you tried v22 on Ubuntu and it works?

**Comment by yu210148** [comment] 2023-04-24 13:53
Yes, that's what is coming up on Ubuntu as well. So it seems that this is
the same as issue 95. I'll note that it affects Debian too and close this
one off as a duplicate of that.

**Comment by yu210148** [comment] 2023-04-24 13:54
Duplicate of issue 95. Also affecting Debian.

**Closed** 2023-04-24 13:53 UTC
